local-phone-apps = AccessoryKeyDispatcher \
                   AntHalService \
                   antradioservice \
                   antstatenotifer \
                   ApplicationsProvider \
                   AudioEffectService \
                   Bluetooth \
                   bootinfo \
                   CameraExtensionPermission \
                   CertInstaller \
                   ContactsImport \
                   CredentialManagerService \
                   CustomizationProvider \
                   CustomizedApplicationInstaller \
                   CustomizedSettings \
                   DefaultCapabilities \
                   DefaultContainerService \
                   enhancedusbux \
                   FaceLock \
                   fast-dormancy-incall \
                   fast-dormancy-wakeup \
                   GenericApplicationInstaller \
                   InfiniteView \
                   Initial-boot-setup \
                   livewallpaperearth \
                   LiveWallpapers \
                   LiveWallpapersPicker \
                   livewaremanager \
                   MediaProvider \
                   MemcardTransportService \
                   Nfc \
                   nfc-handover \
                   NoiseField \
                   PackageInstaller \
                   PowerSaveModule \
                   qcsemcservice \
                   Radio3 \
                   SemcCamera3D \
                   SemcCameraUI \
                   SemcHdmiControlService \
                   SemcSettings \
                   SemcSimDetection \
                   SemcTvLauncher \
                   ServiceMenu \
                   SoundEnhancement \
                   usb-mtp-backup-transport \
                   usb-mtp-marlin-wrapper \
                   usb-mtp-update-wrapper \
                   usb-mtp-vendor-extension-service \
                   usbotg \
                   UsbTransportService \
                   UserDictionaryProvider \
                   VpnDialogs \
                   WapiCustomization \
                   WapPush 
